- name: Install Nginx
  yum:
    name=nginx
    state=latest
  notify:
    - nginx systemd
- name: Replace nginx.conf
  template:
    src=templates/nginx.conf
    dest=/etc/nginx/nginx.conf
- name: Add virtual domain
     src=templates/nginx_vhosts.conf
    dest=/etc/nginx/conf.d/redirect.conf
   notify:
    - nginx restart